# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('date_taken', models.DateTimeField(null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy', models.IntegerField()),
                ('secret', models.CharField(max_length=100, null=True)),
                ('server', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sort.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_sorted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_sorted', models.BooleanField(default=False)),
                ('target_pictured', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('photos', models.ManyToManyField(to='sort.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_sorted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_sorted', models.BooleanField(default=False)),
                ('useful', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
                ('targets', models.ManyToManyField(to='sort.Target')),
            ],
        ),
        migrations.AddField(
            model_name='tag_sorted',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort.Target'),
        ),
        migrations.AddField(
            model_name='tag',
            name='targets',
            field=models.ManyToManyField(through='sort.Tag_sorted', to='sort.Target'),
        ),
        migrations.AddField(
            model_name='photo_sorted',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort.Target'),
        ),
        migrations.AddField(
            model_name='photo',
            name='targets',
            field=models.ManyToManyField(through='sort.Photo_sorted', to='sort.Target'),
        ),
    ]
