# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sort.Term'),
        ),
    ]
